Repository silverfin/silverfin-cli, pull requests merged in 2023-10, with the labels that each got.

#77 Readme: Important considerations
  README.md
Labels: documentation

#81 Make tests pass on an empty liquid testing YAML
  lib/liquidTestRunner.js
  package.json
Labels: bug

#59 Verbose flag
  bin/cli.js
  index.js
  lib/api/firmCredentials.js
  lib/api/sfApi.js
  lib/cli/cliUpdates.js
  lib/cli/devMode.js
  lib/cli/stats.js
  lib/cli/utils.js
  lib/liquidTestGenerator.js
  lib/liquidTestRunner.js
  lib/templates/reconciliationText.js
  lib/utils/apiUtils.js
  lib/utils/errorUtils.js
  lib/utils/fsUtils.js
  lib/utils/liquidTestUtils.js
  lib/utils/liquidUtils.js
  lib/utils/templateUtils.js
  package-lock.json
  package.json
  yarn.lock
Labels: feature request

#84 Fix mkdir so complete path is always created + show success message on shared part import
  index.js
  lib/templates/sharedPart.js
  lib/utils/fsUtils.js
  package.json
Labels: bug
