Repository silverfin/silverfin-cli, pull requests merged in 2023-09, with the labels that each got.

#56 Refactor code
  .gitignore
  bin/cli.js
  index.js
  lib/api/sfApi.js
  lib/cli/cliUpdates.js
  lib/cli/devMode.js
  lib/liquidTestGenerator.js
  lib/liquidTestRunner.js
  lib/reconciliationText.js
  lib/sharedPart.js
  lib/utils/apiUtils.js
  lib/utils/fsUtils.js
  lib/utils/liquidTestUtils.js
  lib/utils/templateUtils.js
  package.json
Labels: maintenance

#60 Remove template.type check for looking up linked shared parts since this missing from most configs
  lib/utils/fsUtils.js
  package.json
Labels: bug

#61 fix typo in reconciliations endpoint + add template data instead of response to argument of save function
  index.js
  lib/api/sfApi.js
  package.json
Labels: bug

#62 shared part main part is the same name as the shared part instead of 'main'
  lib/sharedPart.js
  package.json
Labels: bug

#63 run update command as sudo by default
  lib/cli/cliUpdates.js
  package.json
Labels: bug

#64 Set CWD correctly
  lib/cli/devMode.js
  lib/utils/fsUtils.js
  package.json
Labels: bug

#58 Store firm name
  lib/api/firmCredentials.js
  lib/api/sfApi.js
  lib/utils/apiUtils.js
  package.json
Labels: feature request

#65 Display firm name next to id
  bin/cli.js
  lib/api/firmCredentials.js
  package.json
Labels: feature request

#57 Message flag
  bin/cli.js
  index.js
  package.json
Labels: feature request

#72 Fix: check present attributes in config
  lib/reconciliationText.js
  lib/sharedPart.js
  package.json
Labels: bug
